name: Publish package to NPM Github Repo
on:
    release:
        types: published

jobs:
    test-publish-package:
        runs-on: ubuntu-latest
        permissions: 
            packages: write
            contents: read
        steps:
        - name: Checkout Repo
          uses: action/checkout@v4
        - name: Setup NodeJS Version - 20.x
          uses: action/setup-node@v4
          with:
            node_version: '20.x'
            registry-url: 'https://npm.pkg.github.com'

        - name: Install Dependencies
          run: npm install

        - name: Publish to Github Registry
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}