name: Deployment Re-useable Workflow

on:
    workflow_call:
        secrets:
          k8s-kubeconfig:
            required: true
          mongodb-password:
            required: true

jobs: 
    reuse-deploy:
        runs-on: ubuntu-latest
        environment: 
          name: development
          url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_URL }}
  
        steps:
          - name: Checkout
            uses: actions/checkout@v4
  
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            continue-on-error: true
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1
  
          - name: Install Kubectl CLI
            uses: azure/setup-kubectl@v4
            with:
              version: 'v1.31.0'
  
          - name: Setup KubeConfig
            uses: azure/k8s-set-context@v3
            with:
              method: kubeconfig
              kubeconfig: ${{ secrets.k8s-kubeconfig }}
  
          # - name: Telnet
          #   run: |
          #      telnet 172.30.1.2 6443
  
          # - name: Check Kubernetes Connectivity
          #   run: |
          #       kubectl cluster-info
          #       kubectl get nodes
  
          - name: Fetching K8s cluster details
            continue-on-error: true
            run: |
               kubectl version --short
               echo --------------------------------------
               kubectl get nodes
  
          - name: Replace Tokens in Manifest Files
            uses: cschleiden/replace-tokens@v1
            with:
              tokenPrefix: '_{_'
              tokenSuffix: '_}_'
              files: '["kubernetes/development/*.yaml"]'
            env:
               NAMESPACE: ${{ vars.NAMESPACE }}
               REPLICAS: ${{ vars.REPLICAS}}
               IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
               INGRESS_IP: 172.232.87.200
  
          - name: Check Files
            run: |
              cat kubernetes/development/*.yaml
  
          - name: Create Mongo DB secrets
            continue-on-error: true
            run: |
              kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
              --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
              --from-literal=MONGO_Username=${{ env.MONGO_Username }} \
              --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
              --save-config \
              --dry-run=client \
              -o yaml | kubectl apply -f .
  
  
  
          - name: Deploy to Dev Env
            continue-on-error: true
            run: |
               kubectl apply -f kubernetes/deployment
  
          - name: Set Up Ingress Host Url
            continue-on-error: true
            id: set-ingress-host-address
            run: |
              echo "APP_INGRESS_URL=$(kubectl -n {{ vars.NAMESPACE }}) get ingress -o jsonpath={.items[0].spec.tls[0].host)"}" >> "$GITHUB_TOKEN"
  